// AUTO-GERADO — manifesto de todos os endpoints de creator.

export interface EndpointDef {
  key: string; group: string; title: string;
  method: "GET" | "POST" | "PUT" | "DELETE";
  path: string; version: string; scopes: string[];
  pathParams: string[]; queryParams: string[]; hasBody: boolean; shopCipher: boolean;
}

export const ENDPOINTS = {
  getCreatorProfile: {"key": "getCreatorProfile", "group": "perfil", "title": "Get Creator Profile", "method": "GET", "path": "/affiliate_creator/202508/profiles", "version": "202508", "scopes": ["creator.affiliate.info", "creator.video.write"], "pathParams": [], "queryParams": [], "hasBody": false, "shopCipher": false} as EndpointDef,
  getShowcaseProducts: {"key": "getShowcaseProducts", "group": "perfil", "title": "Get Showcase Products", "method": "GET", "path": "/affiliate_creator/202405/showcases/products", "version": "202405", "scopes": ["creator.showcase.read", "creator.video.write"], "pathParams": [], "queryParams": ["page_size", "page_token", "origin"], "hasBody": false, "shopCipher": false} as EndpointDef,
  addShowcaseProducts: {"key": "addShowcaseProducts", "group": "perfil", "title": "Add Showcase Products", "method": "POST", "path": "/affiliate_creator/202405/showcases/products/add", "version": "202405", "scopes": ["creator.showcase.write", "creator.video.write"], "pathParams": [], "queryParams": [], "hasBody": true, "shopCipher": false} as EndpointDef,
  removeShowcaseProducts: {"key": "removeShowcaseProducts", "group": "perfil", "title": "Remove Showcase Products", "method": "DELETE", "path": "/affiliate_creator/202409/showcases/products", "version": "202409", "scopes": ["creator.showcase.write"], "pathParams": [], "queryParams": [], "hasBody": true, "shopCipher": false} as EndpointDef,
  topShowcaseProducts: {"key": "topShowcaseProducts", "group": "perfil", "title": "Top Showcase Products", "method": "POST", "path": "/affiliate_creator/202409/showcases/products/top", "version": "202409", "scopes": ["creator.showcase.write"], "pathParams": [], "queryParams": [], "hasBody": true, "shopCipher": false} as EndpointDef,
  searchCreatorAffiliateOrders: {"key": "searchCreatorAffiliateOrders", "group": "ganhos", "title": "Search Creator Affiliate Orders", "method": "POST", "path": "/affiliate_creator/202410/orders/search", "version": "202410", "scopes": ["creator.affiliate_collaboration.read"], "pathParams": [], "queryParams": ["page_token", "page_size"], "hasBody": true, "shopCipher": false} as EndpointDef,
  creatorSearchAffiliateTraceOrders: {"key": "creatorSearchAffiliateTraceOrders", "group": "ganhos", "title": "Creator Search Affiliate Trace Orders", "method": "POST", "path": "/affiliate_creator/202505/orders/trace/search", "version": "202505", "scopes": ["creator.affiliate.share_link.read"], "pathParams": [], "queryParams": ["page_token", "page_size"], "hasBody": true, "shopCipher": false} as EndpointDef,
  creatorSearchOpenCollaborationProduct: {"key": "creatorSearchOpenCollaborationProduct", "group": "descoberta", "title": "Creator Search Open Collaboration Product", "method": "POST", "path": "/affiliate_creator/202405/open_collaborations/products/search", "version": "202405", "scopes": ["creator.affiliate_collaboration.read"], "pathParams": [], "queryParams": ["page_token", "page_size", "sort_field", "sort_order"], "hasBody": true, "shopCipher": false} as EndpointDef,
  getOpenCollaborationProductListByProductIds: {"key": "getOpenCollaborationProductListByProductIds", "group": "descoberta", "title": "Get Open Collaboration Product List By Product Ids", "method": "POST", "path": "/affiliate_creator/202509/open_collaborations/products", "version": "202509", "scopes": ["creator.affiliate_collaboration.read"], "pathParams": [], "queryParams": ["product_ids"], "hasBody": false, "shopCipher": false} as EndpointDef,
  // Adicionado manualmente (o gerador nao existe mais): endpoint presente no OAS
  // oficial e ativo na regiao BR, ao contrario do open_collaborations/products/search,
  // que responde 98001004 "unauthorized region" para creators registrados no Brasil.
  creatorSelectAffiliateProduct: {"key": "creatorSelectAffiliateProduct", "group": "descoberta", "title": "Creator Select Affiliate Product", "method": "POST", "path": "/affiliate_creator/202501/selection/products/search", "version": "202501", "scopes": ["creator.affiliate_collaboration.read"], "pathParams": [], "queryParams": ["page_token", "page_size"], "hasBody": true, "shopCipher": false} as EndpointDef,
  searchCreatorTargetCollaborations: {"key": "searchCreatorTargetCollaborations", "group": "descoberta", "title": "Search Creator Target Collaborations", "method": "POST", "path": "/affiliate_creator/202405/target_collaborations/search", "version": "202405", "scopes": ["creator.affiliate_collaboration.read"], "pathParams": [], "queryParams": ["page_token", "page_size"], "hasBody": true, "shopCipher": false} as EndpointDef,
  getCreatorApplicableSampleLabel: {"key": "getCreatorApplicableSampleLabel", "group": "amostras", "title": "Get Creator Applicable Sample Label", "method": "GET", "path": "/affiliate_creator/202412/samples/labels", "version": "202412", "scopes": ["creator.affiliate_collaboration.read"], "pathParams": [], "queryParams": ["product_id"], "hasBody": false, "shopCipher": false} as EndpointDef,
  searchCreatorSampleApplications: {"key": "searchCreatorSampleApplications", "group": "amostras", "title": "Search Creator Sample Applications", "method": "POST", "path": "/affiliate_creator/202412/sample_applications/search", "version": "202412", "scopes": ["creator.affiliate_collaboration.read"], "pathParams": [], "queryParams": ["page_token", "page_size"], "hasBody": true, "shopCipher": false} as EndpointDef,
  getCreatorSampleApplicationDetail: {"key": "getCreatorSampleApplicationDetail", "group": "amostras", "title": "Get Creator Sample Application Detail", "method": "POST", "path": "/affiliate_creator/202412/sample_applications/single_query", "version": "202412", "scopes": ["creator.affiliate_collaboration.read"], "pathParams": [], "queryParams": [], "hasBody": true, "shopCipher": false} as EndpointDef,
  creatorSearchSampleApplicationFulfillments: {"key": "creatorSearchSampleApplicationFulfillments", "group": "amostras", "title": "Creator Search Sample Application Fulfillments", "method": "POST", "path": "/affiliate_creator/202409/sample_applications/fulfillments/search", "version": "202409", "scopes": ["creator.affiliate_collaboration.read"], "pathParams": [], "queryParams": ["sort_order", "sort_field"], "hasBody": true, "shopCipher": false} as EndpointDef,
  // Adicionados manualmente apos auditoria (o gerador nao existe mais). Os tres
  // respondem com os escopos atuais, verificado em producao.
  creatorGetSampleRequestDeeplink: {"key": "creatorGetSampleRequestDeeplink", "group": "amostras", "title": "Creator Get Sample Request Deeplink", "method": "GET", "path": "/affiliate_creator/202512/samples/deeplink", "version": "202512", "scopes": ["creator.affiliate_collaboration.read"], "pathParams": [], "queryParams": ["product_id", "sku_id"], "hasBody": false, "shopCipher": false} as EndpointDef,
  checkAnchorPrerequisites: {"key": "checkAnchorPrerequisites", "group": "estudio", "title": "Check Anchor Prerequisites", "method": "POST", "path": "/affiliate/202402/anchors/prerequisite_check", "version": "202402", "scopes": ["creator.affiliate_collaboration.read"], "pathParams": [], "queryParams": [], "hasBody": true, "shopCipher": false} as EndpointDef,
  checkAnchorContent: {"key": "checkAnchorContent", "group": "estudio", "title": "Check Anchor Content", "method": "POST", "path": "/affiliate/202403/anchors/content_check", "version": "202403", "scopes": ["creator.affiliate_collaboration.read"], "pathParams": [], "queryParams": [], "hasBody": true, "shopCipher": false} as EndpointDef,
  creatorGenerateGeneralLink: {"key": "creatorGenerateGeneralLink", "group": "links", "title": "Creator Generate General Link", "method": "POST", "path": "/affiliate_creator/202505/affiliate_sharing_links/general_publishers/generate_batch", "version": "202505", "scopes": ["creator.affiliate.share_link.read"], "pathParams": [], "queryParams": [], "hasBody": true, "shopCipher": false} as EndpointDef,
  creatorGeneratePublisherLink: {"key": "creatorGeneratePublisherLink", "group": "links", "title": "Creator Generate Publisher Link", "method": "POST", "path": "/affiliate_creator/202504/affiliate_sharing_links/publisher/{publisher_id}/generate_batch", "version": "202504", "scopes": ["creator.affiliate.share_link.read"], "pathParams": ["publisher_id"], "queryParams": [], "hasBody": true, "shopCipher": false} as EndpointDef,
  getShopProducts: {"key": "getShopProducts", "group": "estudio", "title": "Get Shop Products", "method": "GET", "path": "/affiliate_creator/202509/shop_products", "version": "202509", "scopes": ["creator.video.write"], "pathParams": [], "queryParams": ["title_keyword", "sort_field", "sort_order", "page_size", "page_token"], "hasBody": false, "shopCipher": false} as EndpointDef,
  searchMusic: {"key": "searchMusic", "group": "estudio", "title": "Search Music", "method": "GET", "path": "/affiliate_creator/202602/music/search", "version": "202602", "scopes": ["creator.video.write"], "pathParams": [], "queryParams": ["keyword", "search_id", "page_token", "page_size", "region", "language"], "hasBody": false, "shopCipher": false} as EndpointDef,
  uploadFileInit: {"key": "uploadFileInit", "group": "estudio", "title": "Upload File Init", "method": "POST", "path": "/open/202512/file/init", "version": "202512", "scopes": ["seller.customer_service", "creator.video.write"], "pathParams": [], "queryParams": ["shop_cipher", "category_asset_cipher"], "hasBody": true, "shopCipher": false} as EndpointDef,
  uploadShoppableVideoFile: {"key": "uploadShoppableVideoFile", "group": "estudio", "title": "Upload Shoppable Video File", "method": "POST", "path": "/affiliate_creator/202505/videos/video_files", "version": "202505", "scopes": ["creator.video.write"], "pathParams": [], "queryParams": [], "hasBody": true, "shopCipher": false} as EndpointDef,
  uploadShoppablePhotoFile: {"key": "uploadShoppablePhotoFile", "group": "estudio", "title": "Upload Shoppable Photo File", "method": "POST", "path": "/affiliate_creator/202511/photos/photo_files", "version": "202511", "scopes": ["creator.video.write"], "pathParams": [], "queryParams": [], "hasBody": true, "shopCipher": false} as EndpointDef,
  precheckVideoContent: {"key": "precheckVideoContent", "group": "estudio", "title": "Precheck Video Content", "method": "POST", "path": "/affiliate_creator/202511/videos/precheck_task", "version": "202511", "scopes": ["creator.video.write"], "pathParams": [], "queryParams": [], "hasBody": true, "shopCipher": false} as EndpointDef,
  getShoppableVideoPrecheckResult: {"key": "getShoppableVideoPrecheckResult", "group": "estudio", "title": "Get Shoppable Video Precheck Result", "method": "GET", "path": "/affiliate_creator/202601/videos/precheck_tasks/{task_id}", "version": "202601", "scopes": ["creator.video.write"], "pathParams": ["task_id"], "queryParams": [], "hasBody": false, "shopCipher": false} as EndpointDef,
  postShoppableVideo: {"key": "postShoppableVideo", "group": "estudio", "title": "Post Shoppable Video", "method": "POST", "path": "/affiliate_creator/202607/videos", "version": "202607", "scopes": ["creator.video.write"], "pathParams": [], "queryParams": [], "hasBody": true, "shopCipher": false} as EndpointDef,
  postShoppablePhotos: {"key": "postShoppablePhotos", "group": "estudio", "title": "Post Shoppable Photos", "method": "POST", "path": "/affiliate_creator/202607/photos", "version": "202607", "scopes": ["creator.video.write"], "pathParams": [], "queryParams": [], "hasBody": true, "shopCipher": false} as EndpointDef,
  getShoppableVideoStatus: {"key": "getShoppableVideoStatus", "group": "estudio", "title": "Get Shoppable Video Status", "method": "GET", "path": "/affiliate_creator/202509/videos/{video_id}/status", "version": "202509", "scopes": ["creator.video.write"], "pathParams": ["video_id"], "queryParams": [], "hasBody": false, "shopCipher": false} as EndpointDef,
  getVideoPerformances: {"key": "getVideoPerformances", "group": "analytics", "title": "Get Video Performances", "method": "GET", "path": "/analytics/202403/videos/performances", "version": "202403", "scopes": ["creator.video.write"], "pathParams": [], "queryParams": ["video_ids", "start_time_ge", "end_time_le"], "hasBody": false, "shopCipher": false} as EndpointDef,
  getLiveRoomCoreStats: {"key": "getLiveRoomCoreStats", "group": "analytics", "title": "Get Live Room Core Stats", "method": "GET", "path": "/analytics/202502/live_rooms/{live_room_id}/core_stats", "version": "202502", "scopes": ["creator.data.live.read.public"], "pathParams": ["live_room_id"], "queryParams": [], "hasBody": false, "shopCipher": false} as EndpointDef,
  getLiveRoomGmvTrend: {"key": "getLiveRoomGmvTrend", "group": "analytics", "title": "Get Live Room GMV Trend", "method": "GET", "path": "/analytics/202502/live_rooms/{live_room_id}/gmv_trend_performances", "version": "202502", "scopes": ["creator.data.live.read.public"], "pathParams": ["live_room_id"], "queryParams": [], "hasBody": false, "shopCipher": false} as EndpointDef,
  getLiveRoomViewTrends: {"key": "getLiveRoomViewTrends", "group": "analytics", "title": "Get Live Room View Trends", "method": "GET", "path": "/analytics/202502/live_rooms/{live_room_id}/view_trend_performances", "version": "202502", "scopes": ["creator.data.live.read.public"], "pathParams": ["live_room_id"], "queryParams": [], "hasBody": false, "shopCipher": false} as EndpointDef,
  getLiveRoomTrafficPerformance: {"key": "getLiveRoomTrafficPerformance", "group": "analytics", "title": "Get Live Room Traffic Performance", "method": "GET", "path": "/analytics/202502/live_rooms/{live_room_id}/traffic_performances", "version": "202502", "scopes": ["creator.data.live.read.public"], "pathParams": ["live_room_id"], "queryParams": [], "hasBody": false, "shopCipher": false} as EndpointDef,
  getLiveRoomInteractiveTrends: {"key": "getLiveRoomInteractiveTrends", "group": "analytics", "title": "Get Live Room Interactive Trends", "method": "GET", "path": "/analytics/202502/live_rooms/{live_room_id}/interactive_trend_performances", "version": "202502", "scopes": ["creator.data.live.read.public"], "pathParams": ["live_room_id"], "queryParams": [], "hasBody": false, "shopCipher": false} as EndpointDef,
  getLiveRoomProductStats: {"key": "getLiveRoomProductStats", "group": "analytics", "title": "Get Live Room Product Stats", "method": "GET", "path": "/analytics/202502/live_rooms/{live_room_id}/product_stats", "version": "202502", "scopes": ["creator.data.live.read.public"], "pathParams": ["live_room_id"], "queryParams": [], "hasBody": false, "shopCipher": false} as EndpointDef,
  getLiveRoomUserPortraits: {"key": "getLiveRoomUserPortraits", "group": "analytics", "title": "Get Live Room User Portraits", "method": "GET", "path": "/analytics/202502/live_rooms/{live_room_id}/user_portraits", "version": "202502", "scopes": ["creator.data.live.read.public"], "pathParams": ["live_room_id"], "queryParams": [], "hasBody": false, "shopCipher": false} as EndpointDef,
  getTokoProductMappers: {"key": "getTokoProductMappers", "group": "toko", "title": "Get Toko Product Mappers", "method": "GET", "path": "/affiliate_creator/202606/toko_product_mappers", "version": "202606", "scopes": [], "pathParams": [], "queryParams": [], "hasBody": true, "shopCipher": false} as EndpointDef,
  tokoProductMapperV2: {"key": "tokoProductMapperV2", "group": "toko", "title": "Toko Product Mapper V2", "method": "POST", "path": "/affiliate_creator/202607/map_toko_product", "version": "202607", "scopes": ["creator.affiliate.share_link.read"], "pathParams": [], "queryParams": [], "hasBody": true, "shopCipher": false} as EndpointDef,
} as const;

export type EndpointKey = keyof typeof ENDPOINTS;
export const ENDPOINT_KEYS = Object.keys(ENDPOINTS) as EndpointKey[];
